// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp5tEorDkCbIZFDvps6gQY2pIadJcxjPg',
    appId: '1:269069343088:web:1a38b10eacd8a2eadcd7b5',
    messagingSenderId: '269069343088',
    projectId: 'medguard-2aadf',
    authDomain: 'medguard-2aadf.firebaseapp.com',
    storageBucket: 'medguard-2aadf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR-S5ZtDF05Sz-GZ4SyMCESHJjc_IaJRU',
    appId: '1:269069343088:android:30cad5593fdd66dddcd7b5',
    messagingSenderId: '269069343088',
    projectId: 'medguard-2aadf',
    storageBucket: 'medguard-2aadf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE-TKB3Es2DKXsEVC3M76bqS-2hddNCao',
    appId: '1:269069343088:ios:04ab337915e3c191dcd7b5',
    messagingSenderId: '269069343088',
    projectId: 'medguard-2aadf',
    storageBucket: 'medguard-2aadf.firebasestorage.app',
    iosClientId:
        '269069343088-fe0u9lc3qr1hm506hol3fir400u3i6g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE-TKB3Es2DKXsEVC3M76bqS-2hddNCao',
    appId: '1:269069343088:ios:04ab337915e3c191dcd7b5',
    messagingSenderId: '269069343088',
    projectId: 'medguard-2aadf',
    storageBucket: 'medguard-2aadf.firebasestorage.app',
    iosClientId:
        '269069343088-fe0u9lc3qr1hm506hol3fir400u3i6g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp5tEorDkCbIZFDvps6gQY2pIadJcxjPg',
    appId: '1:269069343088:web:0b1b313ea7247cc8dcd7b5',
    messagingSenderId: '269069343088',
    projectId: 'medguard-2aadf',
    authDomain: 'medguard-2aadf.firebaseapp.com',
    storageBucket: 'medguard-2aadf.firebasestorage.app',
  );
}
